server:
  port : 8080
spring:
  application: 
    name : Course_service_JDBC

  datasource: 
    url : ${datasource.url}
    username : ${datasource.username}
    password : ${datasource.password}
    
